import { renderProjectCanvas } from './pngExport.js'

export function generateMonochromeBytes(imageData, options = {}) {
  const { width, height, data } = imageData
  const threshold = options.threshold !== undefined ? options.threshold : 128
  const invert = Boolean(options.invert)
  const format = options.format || 'adafruit' // 'adafruit', 'u8g2', 'xbm'

  function isPixelOn(x, y) {
    if (x >= width || y >= height) return false
    const idx = (y * width + x) * 4
    const r = data[idx]
    const g = data[idx + 1]
    const b = data[idx + 2]
    const luminance = 0.299 * r + 0.587 * g + 0.114 * b
    const isBright = luminance >= threshold
    return invert ? !isBright : isBright
  }

  const bytes = []

  if (format === 'u8g2') {
    // Vertical Page Mode (8 vertical pixels per byte, LSB first)
    const pages = Math.ceil(height / 8)
    for (let p = 0; p < pages; p++) {
      for (let x = 0; x < width; x++) {
        let byteVal = 0
        for (let bit = 0; bit < 8; bit++) {
          const y = p * 8 + bit
          if (isPixelOn(x, y)) {
            byteVal |= (1 << bit)
          }
        }
        bytes.push(byteVal)
      }
    }
  } else if (format === 'xbm') {
    // XBM Format: Horizontal, LSB first
    const bytesPerRow = Math.ceil(width / 8)
    for (let y = 0; y < height; y++) {
      for (let b = 0; b < bytesPerRow; b++) {
        let byteVal = 0
        for (let bit = 0; bit < 8; bit++) {
          const x = b * 8 + bit
          if (x < width && isPixelOn(x, y)) {
            byteVal |= (1 << bit)
          }
        }
        bytes.push(byteVal)
      }
    }
  } else {
    // Default Adafruit_GFX: Horizontal, MSB first
    const bytesPerRow = Math.ceil(width / 8)
    for (let y = 0; y < height; y++) {
      for (let b = 0; b < bytesPerRow; b++) {
        let byteVal = 0
        for (let bit = 0; bit < 8; bit++) {
          const x = b * 8 + bit
          if (x < width && isPixelOn(x, y)) {
            byteVal |= (1 << (7 - bit))
          }
        }
        bytes.push(byteVal)
      }
    }
  }

  return new Uint8Array(bytes)
}

export function formatCSource(options = {}) {
  const {
    bitmapBytes,
    width,
    height,
    format = 'adafruit',
    variableName = 'lcd_mockup_bitmap',
    projectName = 'LCD Mockup',
  } = options

  const cleanVar = variableName.replace(/[^a-zA-Z0-9_]/g, '_') || 'lcd_mockup_bitmap'
  const macroName = cleanVar.toUpperCase()
  const bytesPerLine = 12

  const hexLines = []
  for (let i = 0; i < bitmapBytes.length; i += bytesPerLine) {
    const chunk = Array.from(bitmapBytes.slice(i, i + bytesPerLine))
      .map(b => '0x' + b.toString(16).padStart(2, '0'))
      .join(', ')
    hexLines.push('  ' + chunk + (i + bytesPerLine < bitmapBytes.length ? ',' : ''))
  }

  let usageComment = ''
  if (format === 'adafruit') {
    usageComment = `// Adafruit_GFX usage:\n// display.drawBitmap(0, 0, ${cleanVar}, ${macroName}_WIDTH, ${macroName}_HEIGHT, 1);`
  } else if (format === 'u8g2') {
    usageComment = `// U8g2 page-mode bitmap usage:\n// u8g2.drawBitmap(0, 0, (${macroName}_WIDTH + 7) / 8, ${macroName}_HEIGHT, ${cleanVar});`
  } else if (format === 'xbm') {
    usageComment = `// U8g2 XBM usage:\n// u8g2.drawXBMP(0, 0, ${macroName}_WIDTH, ${macroName}_HEIGHT, ${cleanVar});`
  }

  if (format === 'xbm') {
    return `// =============================================================================\n` +
      `// Generated by LCD Mockup Studio (https://github.com/MitraZahiri/lcd-mockup-studio)\n` +
      `// Project: ${projectName}\n` +
      `// Format: XBM (X BitMap / LSB-first horizontal)\n` +
      `// Size: ${width} x ${height} px (${bitmapBytes.length} bytes)\n` +
      `// ${usageComment.replace(/\n/g, '\n// ')}\n` +
      `// =============================================================================\n\n` +
      `#define ${macroName}_WIDTH ${width}\n` +
      `#define ${macroName}_HEIGHT ${height}\n\n` +
      `static const unsigned char ${cleanVar}[] = {\n` +
      hexLines.join('\n') + `\n` +
      `};\n`
  }

  return `// =============================================================================\n` +
    `// Generated by LCD Mockup Studio (https://github.com/MitraZahiri/lcd-mockup-studio)\n` +
    `// Project: ${projectName}\n` +
    `// Format: ${format.toUpperCase()} (${format === 'u8g2' ? 'Vertical 8-px Pages' : 'Horizontal MSB-first'})\n` +
    `// Size: ${width} x ${height} px (${bitmapBytes.length} bytes)\n` +
    `// =============================================================================\n\n` +
    `#ifndef ${macroName}_H\n` +
    `#define ${macroName}_H\n\n` +
    `#include <stdint.h>\n\n` +
    `#if defined(__AVR__)\n` +
    `  #include <avr/pgmspace.h>\n` +
    `#elif defined(ESP8266) || defined(ESP32)\n` +
    `  #include <pgmspace.h>\n` +
    `#else\n` +
    `  #ifndef PROGMEM\n` +
    `    #define PROGMEM\n` +
    `  #endif\n` +
    `#endif\n\n` +
    `#define ${macroName}_WIDTH  ${width}\n` +
    `#define ${macroName}_HEIGHT ${height}\n\n` +
    `${usageComment}\n\n` +
    `static const uint8_t PROGMEM ${cleanVar}[] = {\n` +
    hexLines.join('\n') + `\n` +
    `};\n\n` +
    `#endif // ${macroName}_H\n`
}

export function renderMonochromeToCanvas(canvas, bitmapBytes, width, height, format = 'adafruit') {
  canvas.width = width
  canvas.height = height
  const ctx = canvas.getContext('2d')
  if (!ctx) return

  const imgData = ctx.createImageData(width, height)
  const d = imgData.data

  function setPixel(x, y, on) {
    if (x >= width || y >= height) return
    const idx = (y * width + x) * 4
    const val = on ? 255 : 20
    d[idx] = val
    d[idx + 1] = on ? 255 : 25
    d[idx + 2] = val
    d[idx + 3] = 255
  }

  if (format === 'u8g2') {
    const pages = Math.ceil(height / 8)
    let byteIdx = 0
    for (let p = 0; p < pages; p++) {
      for (let x = 0; x < width; x++) {
        const byteVal = bitmapBytes[byteIdx++] || 0
        for (let bit = 0; bit < 8; bit++) {
          const y = p * 8 + bit
          setPixel(x, y, (byteVal & (1 << bit)) !== 0)
        }
      }
    }
  } else if (format === 'xbm') {
    const bytesPerRow = Math.ceil(width / 8)
    let byteIdx = 0
    for (let y = 0; y < height; y++) {
      for (let b = 0; b < bytesPerRow; b++) {
        const byteVal = bitmapBytes[byteIdx++] || 0
        for (let bit = 0; bit < 8; bit++) {
          const x = b * 8 + bit
          if (x < width) {
            setPixel(x, y, (byteVal & (1 << bit)) !== 0)
          }
        }
      }
    }
  } else {
    const bytesPerRow = Math.ceil(width / 8)
    let byteIdx = 0
    for (let y = 0; y < height; y++) {
      for (let b = 0; b < bytesPerRow; b++) {
        const byteVal = bitmapBytes[byteIdx++] || 0
        for (let bit = 0; bit < 8; bit++) {
          const x = b * 8 + bit
          if (x < width) {
            setPixel(x, y, (byteVal & (1 << (7 - bit))) !== 0)
          }
        }
      }
    }
  }

  ctx.putImageData(imgData, 0, 0)
}

export function initCExport(state) {
  const exportBtn = document.querySelector('#export-c')
  const modal = document.querySelector('#c-export-modal')
  if (!exportBtn || !modal) return

  const closeBtn = modal.querySelector('#c-export-close')
  const formatSelect = modal.querySelector('#c-export-format')
  const thresholdSlider = modal.querySelector('#c-export-threshold')
  const thresholdVal = modal.querySelector('#c-export-threshold-val')
  const invertCheck = modal.querySelector('#c-export-invert')
  const codeArea = modal.querySelector('#c-export-code')
  const copyBtn = modal.querySelector('#c-export-copy')
  const downloadBtn = modal.querySelector('#c-export-download')
  const previewCanvas = modal.querySelector('#c-export-preview')
  const resolutionInfo = modal.querySelector('#c-export-resolution')

  let currentCode = ''
  let currentBytes = null

  function updateExport() {
    const { width, height } = state.display
    const offscreen = document.createElement('canvas')
    const project = structuredClone({ display: state.display, elements: state.elements })
    renderProjectCanvas(project, offscreen)

    const ctx = offscreen.getContext('2d')
    if (!ctx) return
    const imageData = ctx.getImageData(0, 0, width, height)

    const format = formatSelect.value
    const threshold = Number(thresholdSlider.value)
    const invert = invertCheck.checked

    thresholdVal.textContent = String(threshold)
    resolutionInfo.textContent = `${width} × ${height} px`

    currentBytes = generateMonochromeBytes(imageData, { threshold, invert, format })
    renderMonochromeToCanvas(previewCanvas, currentBytes, width, height, format)

    currentCode = formatCSource({
      bitmapBytes: currentBytes,
      width,
      height,
      format,
      variableName: 'lcd_mockup_bitmap',
      projectName: 'LCD Mockup',
    })

    codeArea.value = currentCode
  }

  exportBtn.addEventListener('click', () => {
    updateExport()
    modal.hidden = false
  })

  closeBtn?.addEventListener('click', () => {
    modal.hidden = true
  })

  formatSelect?.addEventListener('change', updateExport)
  thresholdSlider?.addEventListener('input', updateExport)
  invertCheck?.addEventListener('change', updateExport)

  copyBtn?.addEventListener('click', async () => {
    if (!currentCode) return
    try {
      await navigator.clipboard.writeText(currentCode)
      const origText = copyBtn.textContent
      copyBtn.textContent = 'Copied!'
      setTimeout(() => {
        copyBtn.textContent = origText
      }, 1500)
    } catch {
      codeArea.select()
      document.execCommand('copy')
    }
  })

  downloadBtn?.addEventListener('click', () => {
    if (!currentCode) return
    const { width, height } = state.display
    const format = formatSelect.value
    const ext = format === 'xbm' ? 'xbm' : 'h'
    const blob = new Blob([currentCode], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `lcd-mockup-${width}x${height}.${ext}`
    document.body.appendChild(link)
    link.click()
    link.remove()
    setTimeout(() => URL.revokeObjectURL(url), 1000)
  })

  window.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && !modal.hidden) {
      modal.hidden = true
    }
  })
}
