import { renderProjectCanvas } from './pngExport.js'
import { snapshotProject } from '../project/projectFormat.js'

export function generateMonochromeBytes(imageData, options = {}) {
  const { width, height, data } = imageData
  const threshold = options.threshold !== undefined ? options.threshold : 128
  const invert = Boolean(options.invert)
  const format = options.format || 'adafruit' // 'adafruit', 'u8g2', 'xbm'

  function isPixelOn(x, y) {
    if (x >= width || y >= height) return false
    const idx = (y * width + x) * 4
    const r = data[idx]
    const g = data[idx + 1]
    const b = data[idx + 2]
    const luminance = 0.299 * r + 0.587 * g + 0.114 * b
    const isBright = luminance >= threshold
    return invert ? !isBright : isBright
  }

  const bytes = []

  const isXbm = format === 'xbm' || format === 'arduino_sketch'
  const isU8g2 = format === 'u8g2'

  if (isU8g2) {
    // Vertical Page Mode (8 vertical pixels per byte, LSB first)
    const pages = Math.ceil(height / 8)
    for (let p = 0; p < pages; p++) {
      for (let x = 0; x < width; x++) {
        let byteVal = 0
        for (let bit = 0; bit < 8; bit++) {
          const y = p * 8 + bit
          if (isPixelOn(x, y)) {
            byteVal |= (1 << bit)
          }
        }
        bytes.push(byteVal)
      }
    }
  } else if (isXbm) {
    // XBM Format: Horizontal, LSB first
    const bytesPerRow = Math.ceil(width / 8)
    for (let y = 0; y < height; y++) {
      for (let b = 0; b < bytesPerRow; b++) {
        let byteVal = 0
        for (let bit = 0; bit < 8; bit++) {
          const x = b * 8 + bit
          if (x < width && isPixelOn(x, y)) {
            byteVal |= (1 << bit)
          }
        }
        bytes.push(byteVal)
      }
    }
  } else {
    // Default Adafruit_GFX & MicroPython framebuf (MONO_HLSB): Horizontal, MSB first
    const bytesPerRow = Math.ceil(width / 8)
    for (let y = 0; y < height; y++) {
      for (let b = 0; b < bytesPerRow; b++) {
        let byteVal = 0
        for (let bit = 0; bit < 8; bit++) {
          const x = b * 8 + bit
          if (x < width && isPixelOn(x, y)) {
            byteVal |= (1 << (7 - bit))
          }
        }
        bytes.push(byteVal)
      }
    }
  }

  return new Uint8Array(bytes)
}

export function formatCSource(options = {}) {
  const {
    bitmapBytes,
    width,
    height,
    format = 'adafruit',
    variableName = 'lcd_mockup_bitmap',
    projectName = 'LCD Mockup',
  } = options

  const cleanVar = variableName.replace(/[^a-zA-Z0-9_]/g, '_') || 'lcd_mockup_bitmap'
  const macroName = cleanVar.toUpperCase()
  const bytesPerLine = 12

  const hexLines = []
  for (let i = 0; i < bitmapBytes.length; i += bytesPerLine) {
    const chunk = Array.from(bitmapBytes.slice(i, i + bytesPerLine))
      .map(b => '0x' + b.toString(16).padStart(2, '0'))
      .join(', ')
    hexLines.push('  ' + chunk + (i + bytesPerLine < bitmapBytes.length ? ',' : ''))
  }

  if (format === 'micropython') {
    return `# =============================================================================\n` +
      `# Generated by LCD Mockup Studio (https://github.com/MitraZahiri/lcd-mockup-studio)\n` +
      `# Project: ${projectName}\n` +
      `# Format: MicroPython framebuf (MONO_HLSB / Horizontal MSB-first)\n` +
      `# Size: ${width} x ${height} px (${bitmapBytes.length} bytes)\n` +
      `# =============================================================================\n\n` +
      `import framebuf\n\n` +
      `${macroName}_WIDTH = ${width}\n` +
      `${macroName}_HEIGHT = ${height}\n\n` +
      `# 1-bit monochrome bitmap buffer\n` +
      `${cleanVar} = bytearray([\n` +
      hexLines.join('\n') + `\n` +
      `])\n\n` +
      `# FrameBuffer object ready for blit():\n` +
      `fb = framebuf.FrameBuffer(${cleanVar}, ${macroName}_WIDTH, ${macroName}_HEIGHT, framebuf.MONO_HLSB)\n\n` +
      `# Example usage with SSD1306 (I2C on ESP32 / Raspberry Pi Pico):\n` +
      `# from machine import Pin, I2C\n` +
      `# import ssd1306\n` +
      `# i2c = I2C(0, scl=Pin(22), sda=Pin(21))\n` +
      `# display = ssd1306.SSD1306_I2C(${macroName}_WIDTH, ${macroName}_HEIGHT, i2c)\n` +
      `# display.blit(fb, 0, 0)\n` +
      `# display.show()\n`
  }

  if (format === 'arduino_sketch') {
    return `// =============================================================================\n` +
      `// Generated by LCD Mockup Studio (https://github.com/MitraZahiri/lcd-mockup-studio)\n` +
      `// Project: ${projectName}\n` +
      `// Complete Ready-to-Flash Arduino Sketch for SSD1306 OLED (128x64 / I2C)\n` +
      `// Size: ${width} x ${height} px (${bitmapBytes.length} bytes)\n` +
      `// =============================================================================\n\n` +
      `#include <Arduino.h>\n` +
      `#include <Wire.h>\n` +
      `#include <U8g2lib.h>\n\n` +
      `// U8g2 constructor: SSD1306 128x64 Noname I2C (Hardware I2C)\n` +
      `U8G2_SSD1306_128X64_NONAME_F_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE);\n\n` +
      `#define ${macroName}_WIDTH  ${width}\n` +
      `#define ${macroName}_HEIGHT ${height}\n\n` +
      `static const unsigned char PROGMEM ${cleanVar}[] = {\n` +
      hexLines.join('\n') + `\n` +
      `};\n\n` +
      `void setup() {\n` +
      `  Serial.begin(115200);\n` +
      `  Wire.begin();\n` +
      `  u8g2.begin();\n\n` +
      `  // Draw the full mockup display\n` +
      `  u8g2.clearBuffer();\n` +
      `  u8g2.drawXBMP(0, 0, ${macroName}_WIDTH, ${macroName}_HEIGHT, ${cleanVar});\n` +
      `  u8g2.sendBuffer();\n\n` +
      `  Serial.println(F("LCD Mockup displayed successfully!"));\n` +
      `}\n\n` +
      `void loop() {\n` +
      `  // Put interactive display updates or sensor polling here\n` +
      `  delay(1000);\n` +
      `}\n`
  }

  let usageComment = ''
  if (format === 'adafruit') {
    usageComment = `// Adafruit_GFX usage:\n// display.drawBitmap(0, 0, ${cleanVar}, ${macroName}_WIDTH, ${macroName}_HEIGHT, 1);`
  } else if (format === 'u8g2') {
    usageComment = `// U8g2 page-mode bitmap usage:\n// u8g2.drawBitmap(0, 0, (${macroName}_WIDTH + 7) / 8, ${macroName}_HEIGHT, ${cleanVar});`
  } else if (format === 'xbm') {
    usageComment = `// U8g2 XBM usage:\n// u8g2.drawXBMP(0, 0, ${macroName}_WIDTH, ${macroName}_HEIGHT, ${cleanVar});`
  }

  if (format === 'xbm') {
    return `// =============================================================================\n` +
      `// Generated by LCD Mockup Studio (https://github.com/MitraZahiri/lcd-mockup-studio)\n` +
      `// Project: ${projectName}\n` +
      `// Format: XBM (X BitMap / LSB-first horizontal)\n` +
      `// Size: ${width} x ${height} px (${bitmapBytes.length} bytes)\n` +
      `// ${usageComment.replace(/\n/g, '\n// ')}\n` +
      `// =============================================================================\n\n` +
      `#define ${macroName}_WIDTH ${width}\n` +
      `#define ${macroName}_HEIGHT ${height}\n\n` +
      `static const unsigned char ${cleanVar}[] = {\n` +
      hexLines.join('\n') + `\n` +
      `};\n`
  }

  return `// =============================================================================\n` +
    `// Generated by LCD Mockup Studio (https://github.com/MitraZahiri/lcd-mockup-studio)\n` +
    `// Project: ${projectName}\n` +
    `// Format: ${format.toUpperCase()} (${format === 'u8g2' ? 'Vertical 8-px Pages' : 'Horizontal MSB-first'})\n` +
    `// Size: ${width} x ${height} px (${bitmapBytes.length} bytes)\n` +
    `// =============================================================================\n\n` +
    `#ifndef ${macroName}_H\n` +
    `#define ${macroName}_H\n\n` +
    `#include <stdint.h>\n\n` +
    `#if defined(__AVR__)\n` +
    `  #include <avr/pgmspace.h>\n` +
    `#elif defined(ESP8266) || defined(ESP32)\n` +
    `  #include <pgmspace.h>\n` +
    `#else\n` +
    `  #ifndef PROGMEM\n` +
    `    #define PROGMEM\n` +
    `  #endif\n` +
    `#endif\n\n` +
    `#define ${macroName}_WIDTH  ${width}\n` +
    `#define ${macroName}_HEIGHT ${height}\n\n` +
    `${usageComment}\n\n` +
    `static const uint8_t PROGMEM ${cleanVar}[] = {\n` +
    hexLines.join('\n') + `\n` +
    `};\n\n` +
    `#endif // ${macroName}_H\n`
}

export function renderMonochromeToCanvas(canvas, bitmapBytes, width, height, format = 'adafruit') {
  canvas.width = width
  canvas.height = height
  const ctx = canvas.getContext('2d')
  if (!ctx) return

  const imgData = ctx.createImageData(width, height)
  const d = imgData.data

  function setPixel(x, y, on) {
    if (x >= width || y >= height) return
    const idx = (y * width + x) * 4
    const val = on ? 255 : 20
    d[idx] = val
    d[idx + 1] = on ? 255 : 25
    d[idx + 2] = val
    d[idx + 3] = 255
  }

  if (format === 'u8g2') {
    const pages = Math.ceil(height / 8)
    let byteIdx = 0
    for (let p = 0; p < pages; p++) {
      for (let x = 0; x < width; x++) {
        const byteVal = bitmapBytes[byteIdx++] || 0
        for (let bit = 0; bit < 8; bit++) {
          const y = p * 8 + bit
          setPixel(x, y, (byteVal & (1 << bit)) !== 0)
        }
      }
    }
  } else if (format === 'xbm') {
    const bytesPerRow = Math.ceil(width / 8)
    let byteIdx = 0
    for (let y = 0; y < height; y++) {
      for (let b = 0; b < bytesPerRow; b++) {
        const byteVal = bitmapBytes[byteIdx++] || 0
        for (let bit = 0; bit < 8; bit++) {
          const x = b * 8 + bit
          if (x < width) {
            setPixel(x, y, (byteVal & (1 << bit)) !== 0)
          }
        }
      }
    }
  } else {
    const bytesPerRow = Math.ceil(width / 8)
    let byteIdx = 0
    for (let y = 0; y < height; y++) {
      for (let b = 0; b < bytesPerRow; b++) {
        const byteVal = bitmapBytes[byteIdx++] || 0
        for (let bit = 0; bit < 8; bit++) {
          const x = b * 8 + bit
          if (x < width) {
            setPixel(x, y, (byteVal & (1 << (7 - bit))) !== 0)
          }
        }
      }
    }
  }

  ctx.putImageData(imgData, 0, 0)
}

export function formatJsonOutput(state, format = 'json_project', pretty = true) {
  if (format === 'json_elements') {
    return JSON.stringify(state.elements || [], null, pretty ? 2 : 0)
  }
  const snapshot = snapshotProject(state, state.name || 'LCD Mockup')
  return JSON.stringify(snapshot, null, pretty ? 2 : 0)
}

export function formatHexOutput(bitmapBytes, format = 'hex_array') {
  if (!bitmapBytes || bitmapBytes.length === 0) return ''

  if (format === 'hex_space') {
    const lines = []
    for (let i = 0; i < bitmapBytes.length; i += 16) {
      const chunk = Array.from(bitmapBytes.slice(i, i + 16))
        .map(b => b.toString(16).padStart(2, '0').toUpperCase())
        .join(' ')
      lines.push(chunk)
    }
    return lines.join('\n')
  }

  if (format === 'hex_raw') {
    return Array.from(bitmapBytes)
      .map(b => b.toString(16).padStart(2, '0').toUpperCase())
      .join('')
  }

  if (format === 'hex_dump') {
    const lines = []
    for (let i = 0; i < bitmapBytes.length; i += 16) {
      const offset = i.toString(16).padStart(8, '0')
      const slice = Array.from(bitmapBytes.slice(i, i + 16))
      const hexParts = []
      let ascii = ''
      for (let j = 0; j < 16; j++) {
        if (j < slice.length) {
          const b = slice[j]
          hexParts.push(b.toString(16).padStart(2, '0'))
          ascii += (b >= 32 && b <= 126) ? String.fromCharCode(b) : '.'
        } else {
          hexParts.push('  ')
        }
      }
      const groupedHex = `${hexParts.slice(0, 4).join(' ')}  ${hexParts.slice(4, 8).join(' ')}  ${hexParts.slice(8, 12).join(' ')}  ${hexParts.slice(12, 16).join(' ')}`
      lines.push(`${offset}: ${groupedHex}  |${ascii}|`)
    }
    return lines.join('\n')
  }

  // Default 'hex_array': C-style comma separated hex bytes
  const bytesPerLine = 12
  const lines = []
  for (let i = 0; i < bitmapBytes.length; i += bytesPerLine) {
    const chunk = Array.from(bitmapBytes.slice(i, i + bytesPerLine))
      .map(b => '0x' + b.toString(16).padStart(2, '0'))
      .join(', ')
    lines.push('  ' + chunk + (i + bytesPerLine < bitmapBytes.length ? ',' : ''))
  }
  return `// Raw Hex Byte Array (${bitmapBytes.length} bytes / ${bitmapBytes.length * 8} bits)\nconst uint8_t hex_bytes[${bitmapBytes.length}] = {\n${lines.join('\n')}\n};`
}

export function formatBase64(canvasOrDataUrl, format = 'base64_dataurl', width = 128, height = 64) {
  let dataUrl = ''
  if (typeof canvasOrDataUrl === 'string') {
    dataUrl = canvasOrDataUrl
  } else if (canvasOrDataUrl && canvasOrDataUrl.toDataURL) {
    dataUrl = canvasOrDataUrl.toDataURL('image/png')
  }

  if (format === 'base64_raw') {
    return dataUrl.replace(/^data:image\/[a-z]+;base64,/, '')
  }

  if (format === 'base64_html') {
    return `<img src="${dataUrl}" width="${width}" height="${height}" alt="LCD Mockup" style="image-rendering: pixelated;" />`
  }

  return dataUrl
}

const CATEGORY_FORMATS = {
  c: [
    { value: 'adafruit', label: 'Adafruit_GFX (Horizontal MSB-first .h)' },
    { value: 'u8g2', label: 'U8g2 / SSD1306 (Vertical 8-px Pages .h)' },
    { value: 'xbm', label: 'XBM (Standard X BitMap / LSB-first .h)' },
    { value: 'arduino_sketch', label: 'Complete Arduino Sketch (.ino)' },
  ],
  json: [
    { value: 'json_project', label: 'Full Project Layout & Elements (.json)' },
    { value: 'json_elements', label: 'Canvas Elements Only Array (.json)' },
  ],
  hex: [
    { value: 'hex_array', label: 'C Hex Array (0x00, 0x1F, ...)' },
    { value: 'hex_space', label: 'Space-Separated Bytes (00 1F FF ...)' },
    { value: 'hex_dump', label: 'Formatted Memory Hex Dump' },
    { value: 'hex_raw', label: 'Continuous Hex Stream (001FFF...)' },
  ],
  micropython: [
    { value: 'micropython', label: 'MicroPython framebuf (ESP32/Pico .py)' },
  ],
  base64: [
    { value: 'base64_dataurl', label: 'PNG Data URI (data:image/png;base64,...)' },
    { value: 'base64_raw', label: 'Raw Base64 Payload String' },
    { value: 'base64_html', label: 'HTML <img> Tag Snippet' },
  ],
}

export function initCExport(state) {
  const exportBtn = document.querySelector('#export-c')
  const modal = document.querySelector('#c-export-modal')
  if (!exportBtn || !modal) return

  const closeBtn = modal.querySelector('#c-export-close')
  const tabBtns = modal.querySelectorAll('.code-tab-btn')
  const formatSelect = modal.querySelector('#c-export-format')
  const thresholdSlider = modal.querySelector('#c-export-threshold')
  const thresholdVal = modal.querySelector('#c-export-threshold-val')
  const invertCheck = modal.querySelector('#c-export-invert')
  const codeArea = modal.querySelector('#c-export-code')
  const copyBtn = modal.querySelector('#c-export-copy')
  const downloadBtn = modal.querySelector('#c-export-download')
  const previewCanvas = modal.querySelector('#c-export-preview')
  const previewContainer = modal.querySelector('#code-preview-container')
  const previewTitle = modal.querySelector('#code-preview-title')
  const resolutionInfo = modal.querySelector('#c-export-resolution')
  const formatBadge = modal.querySelector('#c-export-format-badge')
  const monoOptions = modal.querySelector('#code-mono-options')
  const jsonOptions = modal.querySelector('#code-json-options')
  const jsonPrettyCheck = modal.querySelector('#code-json-pretty')

  let currentCategory = 'c'
  let currentCode = ''
  let currentBytes = null

  function populateFormatSelect(category) {
    if (!formatSelect) return
    const options = CATEGORY_FORMATS[category] || CATEGORY_FORMATS.c
    formatSelect.innerHTML = ''
    for (const opt of options) {
      const el = document.createElement('option')
      el.value = opt.value
      el.textContent = opt.label
      formatSelect.appendChild(el)
    }
  }

  function setCategory(category) {
    currentCategory = category
    tabBtns.forEach(btn => {
      btn.classList.toggle('active', btn.dataset.tab === category)
    })
    populateFormatSelect(category)

    if (monoOptions && jsonOptions) {
      if (category === 'json') {
        monoOptions.hidden = true
        monoOptions.style.display = 'none'
        jsonOptions.hidden = false
        jsonOptions.style.display = 'flex'
        if (previewContainer) previewContainer.style.display = 'none'
        if (previewTitle) previewTitle.style.display = 'none'
      } else {
        monoOptions.hidden = false
        monoOptions.style.display = 'flex'
        jsonOptions.hidden = true
        jsonOptions.style.display = 'none'
        if (previewContainer) previewContainer.style.display = 'flex'
        if (previewTitle) previewTitle.style.display = 'block'
      }
    }

    if (formatBadge) {
      const labels = {
        c: 'C / C++',
        json: 'JSON',
        hex: 'Hex Code',
        micropython: 'Python',
        base64: 'Base64',
      }
      formatBadge.textContent = labels[category] || 'Code'
    }

    updateExport()
  }

  function updateExport() {
    const { width, height } = state.display
    const offscreen = document.createElement('canvas')
    const project = structuredClone({ display: state.display, elements: state.elements })
    renderProjectCanvas(project, offscreen)

    const ctx = offscreen.getContext('2d')
    if (!ctx) return
    const imageData = ctx.getImageData(0, 0, width, height)

    const format = formatSelect ? formatSelect.value : 'adafruit'
    const threshold = thresholdSlider ? Number(thresholdSlider.value) : 128
    const invert = invertCheck ? invertCheck.checked : false

    if (thresholdVal) thresholdVal.textContent = String(threshold)
    if (resolutionInfo) resolutionInfo.textContent = `${width} × ${height} px`

    // Update JSON summary card if present
    const jsonRes = modal.querySelector('#json-info-res')
    const jsonCount = modal.querySelector('#json-info-count')
    const jsonBg = modal.querySelector('#json-info-bg')
    if (jsonRes) jsonRes.textContent = `${width} × ${height} px`
    if (jsonCount) jsonCount.textContent = `${state.elements?.length || 0} elements`
    if (jsonBg) jsonBg.textContent = state.display?.background || '#000000'

    if (currentCategory === 'json') {
      const pretty = jsonPrettyCheck ? jsonPrettyCheck.checked : true
      currentCode = formatJsonOutput(state, format, pretty)
      if (codeArea) codeArea.value = currentCode
      if (copyBtn) copyBtn.textContent = '📋 Copy JSON Code'
      if (downloadBtn) downloadBtn.textContent = '⭳ Download .json File'
      return
    }

    // For image-based formats (c, hex, micropython, base64)
    const previewFormat = (format === 'arduino_sketch' || format === 'xbm') ? 'xbm' : 'adafruit'
    currentBytes = generateMonochromeBytes(imageData, { threshold, invert, format: previewFormat })
    if (previewCanvas) {
      renderMonochromeToCanvas(previewCanvas, currentBytes, width, height, previewFormat)
    }

    if (currentCategory === 'hex') {
      currentCode = formatHexOutput(currentBytes, format)
      if (copyBtn) copyBtn.textContent = '📋 Copy Hex Code'
      if (downloadBtn) downloadBtn.textContent = '⭳ Download .hex File'
    } else if (currentCategory === 'micropython') {
      currentCode = formatCSource({
        bitmapBytes: currentBytes,
        width,
        height,
        format: 'micropython',
        variableName: 'lcd_mockup_bitmap',
        projectName: 'LCD Mockup',
      })
      if (copyBtn) copyBtn.textContent = '📋 Copy Python Code'
      if (downloadBtn) downloadBtn.textContent = '⭳ Download .py Script'
    } else if (currentCategory === 'base64') {
      currentCode = formatBase64(previewCanvas || offscreen, format, width, height)
      if (copyBtn) copyBtn.textContent = '📋 Copy Base64'
      if (downloadBtn) downloadBtn.textContent = '⭳ Download .txt File'
    } else {
      // Default: C / C++
      currentCode = formatCSource({
        bitmapBytes: currentBytes,
        width,
        height,
        format,
        variableName: 'lcd_mockup_bitmap',
        projectName: 'LCD Mockup',
      })
      if (copyBtn) {
        if (format === 'arduino_sketch') copyBtn.textContent = '📋 Copy Arduino Sketch'
        else copyBtn.textContent = '📋 Copy C Code'
      }
      if (downloadBtn) {
        if (format === 'arduino_sketch') downloadBtn.textContent = '⭳ Download .ino Sketch'
        else if (format === 'xbm') downloadBtn.textContent = '⭳ Download .xbm File'
        else downloadBtn.textContent = '⭳ Download .h Header'
      }
    }

    if (codeArea) codeArea.value = currentCode
  }

  function openModal() {
    setCategory(currentCategory || 'c')
    modal.removeAttribute('hidden')
    modal.hidden = false
    modal.classList.add('open')
    modal.style.display = 'flex'
  }

  function closeModal() {
    modal.setAttribute('hidden', '')
    modal.hidden = true
    modal.classList.remove('open')
    modal.style.display = 'none'
  }

  // Ensure closed on init
  closeModal()

  exportBtn.addEventListener('click', openModal)
  closeBtn?.addEventListener('click', closeModal)

  // Clicking backdrop outside modal dialog closes it
  modal.addEventListener('click', (e) => {
    if (e.target === modal) {
      closeModal()
    }
  })

  // Category tab clicks
  tabBtns.forEach(btn => {
    btn.addEventListener('click', () => {
      setCategory(btn.dataset.tab)
    })
  })

  formatSelect?.addEventListener('change', updateExport)
  thresholdSlider?.addEventListener('input', updateExport)
  invertCheck?.addEventListener('change', updateExport)
  jsonPrettyCheck?.addEventListener('change', updateExport)

  copyBtn?.addEventListener('click', async () => {
    if (!currentCode) return
    try {
      await navigator.clipboard.writeText(currentCode)
      const origText = copyBtn.textContent
      copyBtn.textContent = '✓ Copied to Clipboard!'
      setTimeout(() => {
        copyBtn.textContent = origText
      }, 1500)
    } catch {
      codeArea.select()
      document.execCommand('copy')
    }
  })

  downloadBtn?.addEventListener('click', () => {
    if (!currentCode) return
    const { width, height } = state.display
    const format = formatSelect ? formatSelect.value : 'c'
    let ext = 'h'
    if (currentCategory === 'json') ext = 'json'
    else if (currentCategory === 'hex') ext = 'hex'
    else if (currentCategory === 'micropython' || format === 'micropython') ext = 'py'
    else if (format === 'arduino_sketch') ext = 'ino'
    else if (format === 'xbm') ext = 'xbm'
    else if (currentCategory === 'base64') ext = 'txt'

    const blob = new Blob([currentCode], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `lcd-mockup-${width}x${height}.${ext}`
    document.body.appendChild(link)
    link.click()
    link.remove()
    setTimeout(() => URL.revokeObjectURL(url), 1000)
  })

  window.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && (modal.classList.contains('open') || !modal.hidden)) {
      closeModal()
    }
  })
}
